### ISSUE TITLE
Fix redirect link (windows)

### ISSUE THREAD

**Issue by ericnak** [gsdenys/ephesoft#9]
Edit the dns name in the hosts from windows system folder.

![capturar](https://cloud.githubusercontent.com/assets/17335545/26314373/295cc8a0-3ee4-11e7-9e16-89dc9f60ae89.PNG)

**Comment by gsdenys** [comment]
Step to reproduce... try to open any file at folder management

![screenshot_1](https://cloud.githubusercontent.com/assets/7230611/26354652/e9c31a60-3f9b-11e7-9132-fda7da18dffc.png)

**Comment by gsdenys** [comment]
Problem solved when set localhost by default. When user wanna use other host they just needs to set the host on container start.

Will be ready in the next build (milestone 2.0) at May 30th
